name: Docker Build & Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Creates .env file
        run: |
          echo "API_URL=${{ secrets.API_URL }}" >> .env
          echo "MAPBOX_TOKEN=${{ secrets.MAPBOX_TOKEN }}" >> .env
          echo ".env file created with API_URL and MAPBOX_TOKEN"

      - name: Login to Docker Hub
        run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"

      - name: Build Docker Image
        run: docker build -t pabloalonso24/store-app:${{ github.sha }} .

      - name: Tag Latest
        run: docker tag pabloalonso24/store-app:${{ github.sha }} pabloalonso24/store-app:latest

      - name: Push Docker Image
        run: |
          docker push pabloalonso24/store-app:${{ github.sha }}
          docker push pabloalonso24/store-app:latest